version: '2'

volumes:
  orderer.atc.com:
  info_department.eastchina.atc.com:
  info_department.northchina.atc.com:
  info_department.airchina.atc.com:
  info_department.csair.atc.com:
  #ca.publisher.atc.com:
  #ca.recipient.atc.com:
  couchdb0.com:
  couchdb1.com:
  couchdb2.com:
  couchdb3.com:
  
networks:
  testwork:
  
services:
  orderer.atc.com:
    container_name: orderer.atc.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ATCOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - COMPOSE_PROJECT_NAME=myfirstfabric
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/atc.com/orderers/orderer.atc.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/atc.com/orderers/orderer.atc.com/tls:/var/hyperledger/orderer/tls
      - orderer.atc.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - testwork
  
  info_department.eastchina.atc.com:
    container_name: info_department.eastchina.atc.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=info_department.eastchina.atc.com
      - CORE_PEER_ADDRESS=info_department.eastchina.atc.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=info_department.eastchina.atc.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
#      - CORE_PEER_GOSSIP_BOOTSTRAP=northchina.publisher.atc.com:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=info_department.eastchina.atc.com:7051
      - CORE_PEER_LOCALMSPID=EastChinaMSP
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - COMPOSE_PROJECT_NAME=myfirstfabric
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/eastchina.atc.com/peers/info_department.eastchina.atc.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/eastchina.atc.com/peers/info_department.eastchina.atc.com/tls:/etc/hyperledger/fabric/tls
      - info_department.eastchina.atc.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    depends_on:
      - orderer.atc.com
      - couchdb0.com
    networks:
      - testwork
      
  info_department.northchina.atc.com:
    container_name: info_department.northchina.atc.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=info_department.northchina.atc.com
      - CORE_PEER_ADDRESS=info_department.northchina.atc.com:7061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7061
      - CORE_PEER_CHAINCODEADDRESS=info_department.northchina.atc.com:7062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
#      - CORE_PEER_GOSSIP_BOOTSTRAP=eastchina.atc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=info_department.northchina.atc.com:7061
      - CORE_PEER_LOCALMSPID=NorthChinaMSP
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - COMPOSE_PROJECT_NAME=myfirstfabric
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/northchina.atc.com/peers/info_department.northchina.atc.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/northchina.atc.com/peers/info_department.northchina.atc.com/tls:/etc/hyperledger/fabric/tls
      - info_department.northchina.atc.com:/var/hyperledger/production
    ports:
      - 7061:7061
      - 7062:7062
      - 7063:7063
    depends_on:
      - orderer.atc.com
      - couchdb1.com
    networks:
      - testwork
      
  info_department.airchina.atc.com:
    container_name: info_department.airchina.atc.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=info_department.airchina.atc.com
      - CORE_PEER_ADDRESS=info_department.airchina.atc.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=info_department.airchina.atc.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
#      - CORE_PEER_GOSSIP_BOOTSTRAP=csair.atc.com:8061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=info_department.airchina.atc.com:8051
      - CORE_PEER_LOCALMSPID=AirChinaMSP
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - COMPOSE_PROJECT_NAME=myfirstfabric
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/airchina.atc.com/peers/info_department.airchina.atc.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/airchina.atc.com/peers/info_department.airchina.atc.com/tls:/etc/hyperledger/fabric/tls
      - info_department.airchina.atc.com:/var/hyperledger/production
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053
    depends_on:
      - orderer.atc.com
      - couchdb2.com
    networks:
      - testwork
      
  info_department.csair.atc.com:
    container_name: info_department.csair.atc.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=info_department.csair.atc.com
      - CORE_PEER_ADDRESS=info_department.csair.atc.com:8061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8061
      - CORE_PEER_CHAINCODEADDRESS=info_department.csair.atc.com:8062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8062
#      - CORE_PEER_GOSSIP_BOOTSTRAP=airchina.atc.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=info_department.csair.atc.com:8061
      - CORE_PEER_LOCALMSPID=CsairMSP
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - COMPOSE_PROJECT_NAME=myfirstfabric
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=123456
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/csair.atc.com/peers/info_department.csair.atc.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/csair.atc.com/peers/info_department.csair.atc.com/tls:/etc/hyperledger/fabric/tls
      - info_department.csair.atc.com:/var/hyperledger/production
    ports:
      - 8061:8061
      - 8062:8062
      - 8063:8063
    depends_on:
      - orderer.atc.com
      - couchdb3.com
    networks:
      - testwork

  couchdb0.com:
    container_name: couchdb0.com
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456 
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 5984:5984
    networks:
      - testwork

  couchdb1.com:
    container_name: couchdb1.com
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456 
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 6984:5984
    networks:
      - testwork

  couchdb2.com:
    container_name: couchdb2.com
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456 
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 7984:5984
    networks:
      - testwork


  couchdb3.com:
    container_name: couchdb3.com
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=123456 
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 8984:5984
    networks:
      - testwork
 
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
    

